package ca.afroman.assets;

public enum AssetType
{
	INVALID,
	
	FILTER,
	
	FONT_BLACK,
	FONT_WHITE,
	FONT_NOBLE,
	
	PLAYER_ONE_RAW,
	PLAYER_ONE_UP,
	PLAYER_ONE_DOWN,
	PLAYER_ONE_LEFT,
	PLAYER_ONE_RIGHT,
	PLAYER_ONE_IDLE_UP,
	PLAYER_ONE_IDLE_DOWN,
	PLAYER_ONE_IDLE_LEFT,
	PLAYER_ONE_IDLE_RIGHT,
	
	PLAYER_TWO_RAW,
	PLAYER_TWO_UP,
	PLAYER_TWO_DOWN,
	PLAYER_TWO_LEFT,
	PLAYER_TWO_RIGHT,
	PLAYER_TWO_IDLE_UP,
	PLAYER_TWO_IDLE_DOWN,
	PLAYER_TWO_IDLE_LEFT,
	PLAYER_TWO_IDLE_RIGHT,
	
	TILE_GRASS,
	TILE_GRASS_INNER_TOPLEFT,
	TILE_GRASS_INNER_TOPRIGHT,
	TILE_GRASS_INNER_BOTTOMLEFT,
	TILE_GRASS_INNER_BOTTOMRIGHT,
	TILE_GRASS_OUTER_TOPLEFT,
	TILE_GRASS_OUTER_TOPRIGHT,
	TILE_GRASS_OUTER_BOTTOMLEFT,
	TILE_GRASS_OUTER_BOTTOMRIGHT,
	TILE_GRASS_OUTER_RIGHT,
	TILE_GRASS_OUTER_LEFT,
	TILE_GRASS_OUTER_BOTTOM,
	TILE_GRASS_OUTER_TOP,
	
	TILE_DIRT,
	
	TILE_WATER,
	
	TILE_WALL,
	TILE_WALL_GRASS,
	
	TILE_AURA,
	
	TILE_ROCK,
	
	BUTTON_PRESSED,
	BUTTON_HOVER,
	BUTTON_NORMAL,
	
	TEXT_FIELD,
	TEXT_FIELD_CLEAR,
	
	AUDIO_BUTTON_PUSH,
	AUDIO_BUTTON_RELEASE,
	AUDIO_MENU_MUSIC;
	
	public static AssetType fromOrdinal(int ordinal)
	{
		if (ordinal < 0 || ordinal > values().length - 1) return null;
		
		return values()[ordinal];
	}
}
