package ca.afroman.packet;

public enum PacketType
{
	INVALID,
	CONFIRM_RECEIVED,
	
	REQUEST_CONNECTION,
	DENY_JOIN,
	ASSIDN_CLIENTID,
	UPDATE_PLAYERLIST,
	SETROLE,
	PLAYER_DISCONNECT,
	STOP_SERVER,
	START_SERVER,
	
	SEND_LEVELS,
	
	INSTANTIATE_LEVEL,
	ADD_LEVEL_ENTITY,
	ADD_LEVEL_TILE,
	ADD_LEVEL_HITBOX,
	ADD_LEVEL_POINTLIGHT,
	ADD_LEVEL_PLAYER,
	
	REMOVE_LEVEL_ENTITY,
	REMOVE_LEVEL_TILE,
	REMOVE_LEVEL_HITBOX,
	REMOVE_LEVEL_POINTLIGHT,
	
	REQUEST_PLAYER_MOVE,
	SET_ENTITY_LOCATION,
	SET_PLAYER_LOCATION;
	
	public static PacketType fromOrdinal(int ordinal)
	{
		if (ordinal < 0 || ordinal > values().length - 1) return null;
		
		return values()[ordinal];
	}
}
